### ISSUE TITLE
esites: Cleanup/Merge Galapagos records [Ecuador] pd 2 - TASK 1

### ISSUE THREAD

**Issue by rondlg** [fieldmuseum/EMu-Documentation#576]
### TASK 1: Cleanup the pd2 records

Notes:
- EMu group = "esites cleanup - Galapagos pd2"
-  Use spelling with diacrits. 
- Rank = Province
- See https://en.wikipedia.org/wiki/Provinces_of_Ecuador

Recommendation: 
- ** NEED TO CHOOSE ONE AND MERGE** 634024 has diacrits but 208328 has a lat/lon 

***

| irn | SummaryData | PolPoliticalRank | Departments | Master |
| --- | --- | --- | --- | --- |
| 697277 | South America, Ecuador, Galapagos Islands (Pacific Ocean) | pd2 | Geology | ? |
| 634023 | South America, Ecuador, Galapagos | pd2 | Fishes-IZ-Insects-Geology | ? |
| 634024 | South America, Ecuador, Galápagos | Province | Insects-Botany | ? |
| 208328 | South America, Ecuador, Galapagos Is. [LL] | pd2 | Bird-Mammals | ? |

**Comment by wyattgaswick** [comment]
For this one I might vote for 634024 since it has the most attachments (697277=9, 634023=207, 634024=370, 208328=17 unless there are some I can't see). I would copy the coordinates over from 208328 but I would vote for them being converted to m instead of km since our IPT uses the Darwin Core field "coordinateUncertaintyInMeters" but maybe that's opening up another topic.

If someone else wants to preserve a different one, that's fine by me as long as it ends up with "Province", diacritics, and coordinates.

**Comment by Amiacalva** [comment]
Fishes would obviously vote for 634023 since less work for us but  . . . 
We don't typically use the diacritics (though could use cleanup -typically is operative word) - they are a pain but in reality whatever works for group.  Pick a master and we will move to that.  
Agree - coordinates added to whatever master is picked.
And the use of m preferred to km.

**Comment by rondlg** [comment]
**DECISION: irn 634024  selected as the master record.** 
- Lat/Long tab data transferred from irn 208328 
- irns 697277, 634023, 208328 merged into 634024 and deleted
